/**
 * S16-SOCIAL-GROUPERR-1 — MÃ lỗi SOCIAL trên dây (`error.code` của envelope API-01 §12).
 *
 * Nguồn sự thật MÃ cho CẢ HAI phía: BE (`apps/api/src/social/social.errors.ts`) gắn mã này vào payload
 * của HttpException qua `socialError(...)`; FE so `ApiError.code` với hằng ở đây, KHÔNG so câu chữ
 * `message` (khuôn `IDEMPOTENCY_ERROR_CODES`).
 *
 * Khoá = ĐÚNG tên khoá của `SOCIAL_ERR` phía BE (một lỗi nghiệp vụ ↔ một khoá). Tập khoá hai bên được
 * ép BẰNG NHAU ở tầng kiểu trong `social.errors.ts` — thêm lỗi mà quên mã là lỗi biên dịch.
 *
 * Hai loại mã:
 *  - **Có số** `SOCIAL-ERR-0xx` — catalog SPEC-16 §12 (`001..022`). Nhiều khoá có thể CHUNG một số
 *    (vd `POST_NOT_FOUND`/`COMMENT_NOT_FOUND`/`REPORT_NOT_FOUND` cùng `001`) — đúng SPEC: một số là một
 *    LUẬT, không phải một câu thông báo.
 *  - **Sentinel có tên** `SOCIAL-ERR-<KHOÁ>` — lỗi SPEC-16 §12 không cấp số. Owner ký O1 (29/09/2026):
 *    KHÔNG đánh số mới (đánh số = sửa SPEC-16 §12); mỗi khoá MỘT sentinel riêng để FE phân biệt được.
 *    Khuôn `ASSET-ERR-NOT-FOUND` · `ROOM-ERR-NOT-FOUND` (API-14/15 §7.4).
 *
 * ⚠️ Mã mang ĐÚNG lượng thông tin của `message` (cùng một khoá sinh ra cả hai) ⇒ gắn mã KHÔNG mở oracle
 * mới: các lý do 404 mà SPEC gộp làm một (bài lạ · tenant khác · đã xoá · hidden) vẫn là MỘT khoá, MỘT mã.
 */
export const SOCIAL_ERROR_CODES = {
  POST_NOT_FOUND: "SOCIAL-ERR-001",
  COMMENT_NOT_FOUND: "SOCIAL-ERR-001",
  WRITE_OUT_OF_AUDIENCE: "SOCIAL-ERR-002",
  NOT_CONTENT_OWNER: "SOCIAL-ERR-003",
  COMMENTS_LOCKED: "SOCIAL-ERR-004",
  REPLY_DEPTH: "SOCIAL-ERR-005",
  REACTION_EMOJI_INVALID: "SOCIAL-ERR-006",
  ATTACHMENT_LIMIT: "SOCIAL-ERR-007",
  ATTACHMENT_INVALID: "SOCIAL-ERR-007",
  AUDIENCE_KEY_MISSING: "SOCIAL-ERR-008",
  AUDIENCE_GROUP_NOT_AVAILABLE: "SOCIAL-ERR-008",
  /** `009` KHÔNG phải lỗi HTTP (mention bị bỏ im lặng, 201 + `droppedMentions[]`) — giữ chỗ cho đủ bảng. */
  MENTION_DROPPED_NOT_AN_ERROR: "SOCIAL-ERR-009",
  NEWS_MANAGE_REQUIRED: "SOCIAL-ERR-010",
  MODERATION_FIELD_DENIED: "SOCIAL-ERR-010",
  ACK_NOT_APPLICABLE: "SOCIAL-ERR-011",
  REPORT_ALREADY_DECIDED: "SOCIAL-ERR-021",
  REPORT_NOT_FOUND: "SOCIAL-ERR-001",
  REPORT_DUPLICATE_OPEN: "SOCIAL-ERR-REPORT-DUPLICATE-OPEN",
  FILE_TARGET_POST_DENIED: "SOCIAL-ERR-FILE-TARGET-POST-DENIED",
  FILE_TARGET_COMMENT_DENIED: "SOCIAL-ERR-FILE-TARGET-COMMENT-DENIED",
  FILE_NOT_OWNED: "SOCIAL-ERR-FILE-NOT-OWNED",
  GROUP_NOT_FOUND: "SOCIAL-ERR-012",
  GROUP_MEMBERSHIP_EXISTS: "SOCIAL-ERR-013",
  GROUP_MEMBER_STATE_MISMATCH: "SOCIAL-ERR-013",
  GROUP_ROLE_REQUIRED: "SOCIAL-ERR-014",
  GROUP_LAST_OWNER: "SOCIAL-ERR-015",
  GROUP_NAME_TAKEN: "SOCIAL-ERR-GROUP-NAME-TAKEN",
  GROUP_MEMBER_NOT_FOUND: "SOCIAL-ERR-GROUP-MEMBER-NOT-FOUND",
  POLL_CLOSED: "SOCIAL-ERR-016",
  POLL_VOTE_DUPLICATE: "SOCIAL-ERR-017",
  POLL_OPTIONS_RANGE: "SOCIAL-ERR-018",
  POLL_OPTION_NOT_FOUND: "SOCIAL-ERR-POLL-OPTION-NOT-FOUND",
  POLL_CLOSES_AT_PAST: "SOCIAL-ERR-POLL-CLOSES-AT-PAST",
  POLL_CREATE_REQUIRED: "SOCIAL-ERR-POLL-CREATE-REQUIRED",
  POLL_WRITE_BUSY: "SOCIAL-ERR-POLL-WRITE-BUSY",
  IDEA_TRANSITION: "SOCIAL-ERR-019",
  IDEA_CREATE_REQUIRED: "SOCIAL-ERR-IDEA-CREATE-REQUIRED",
  KUDOS_CREATE_REQUIRED: "SOCIAL-ERR-KUDOS-CREATE-REQUIRED",
  IDEA_APPROVE_REQUIRED: "SOCIAL-ERR-020",
  KUDOS_BADGE_INVALID: "SOCIAL-ERR-022",
  IDEA_REJECT_NOTE_REQUIRED: "SOCIAL-ERR-IDEA-REJECT-NOTE-REQUIRED",
  KUDOS_SELF_RECIPIENT: "SOCIAL-ERR-KUDOS-SELF-RECIPIENT",
  KUDOS_RECIPIENT_LIMIT: "SOCIAL-ERR-KUDOS-RECIPIENT-LIMIT",
  KUDOS_RECIPIENT_INVALID: "SOCIAL-ERR-KUDOS-RECIPIENT-INVALID",
  KUDOS_OFFICIAL_DENIED: "SOCIAL-ERR-KUDOS-OFFICIAL-DENIED",
  REPORT_ACTION_DENIED: "SOCIAL-ERR-REPORT-ACTION-DENIED",
  REPORT_ACTION_INVALID_FOR_TARGET: "SOCIAL-ERR-REPORT-ACTION-INVALID-FOR-TARGET",
  REPORT_ACTION_TARGET_UNAVAILABLE: "SOCIAL-ERR-REPORT-ACTION-TARGET-UNAVAILABLE",
  REPORT_BUSY: "SOCIAL-ERR-REPORT-BUSY",
  KUDOS_BADGE_CODE_TAKEN: "SOCIAL-ERR-KUDOS-BADGE-CODE-TAKEN",
  KUDOS_BADGE_NOT_FOUND: "SOCIAL-ERR-KUDOS-BADGE-NOT-FOUND",
  STATS_UNIT_OUT_OF_SCOPE: "SOCIAL-ERR-STATS-UNIT-OUT-OF-SCOPE",
  RESTORE_GROUP_DELETED: "SOCIAL-ERR-RESTORE-GROUP-DELETED",
  // ── S16-SOCIAL-GROUPERR-1 (D11): 4 chuỗi trước đây sống NGOÀI bảng, nay có mã ──
  POST_TYPE_PAIR_DESYNC: "SOCIAL-ERR-POST-TYPE-PAIR-DESYNC",
  CURSOR_INVALID: "SOCIAL-ERR-CURSOR-INVALID",
  CURSOR_FILTER_MISMATCH: "SOCIAL-ERR-CURSOR-FILTER-MISMATCH",
  PIN_NEWS_ONLY: "SOCIAL-ERR-PIN-NEWS-ONLY",
} as const satisfies Record<string, `SOCIAL-ERR-${string}`>;

export type SocialErrorKey = keyof typeof SOCIAL_ERROR_CODES;
export type SocialErrorCode = (typeof SOCIAL_ERROR_CODES)[SocialErrorKey];

const SOCIAL_ERROR_CODE_SET: ReadonlySet<string> = new Set(Object.values(SOCIAL_ERROR_CODES));

/**
 * `true` ⇔ `code` là một mã SOCIAL đã khai. Dùng để phân biệt lỗi SOCIAL với lỗi dùng chung đi qua
 * CÙNG route (tầng-1 `PermissionGuard` `AUTH-ERR-FORBIDDEN`, Zod `VALIDATION-ERR-001`, idempotency
 * `REQUEST-ERR-IDEMPOTENCY-*`) — những lỗi đó KHÔNG mang mã SOCIAL.
 */
export function isSocialErrorCode(code: unknown): code is SocialErrorCode {
  return typeof code === "string" && SOCIAL_ERROR_CODE_SET.has(code);
}
