import { fileURLToPath } from "node:url";
import swc from "unplugin-swc";
import { configDefaults, defineConfig } from "vitest/config";

// Build the test env, resolving the target Postgres DB from process.env FIRST so per-lane isolation
// works. Precedence: explicit DATABASE_URL/DIRECT/WORKER from the env > LANE_DB (lane DB name) >
// shared `mediaos` fallback (CI ephemeral / master). Vitest's `env` literals override process.env, so
// resolving here (Node config ctx, where process.env is authoritative) is what makes LANE_DB take effect.
function laneDbEnv(): Record<string, string> {
  const host = process.env.PG_HOSTPORT ?? "localhost:5432";
  const db = process.env.LANE_DB ?? "mediaos";
  const url = process.env.DATABASE_URL ?? `postgres://mediaos_app:changeme_app_only@${host}/${db}`;
  const directUrl =
    process.env.DATABASE_DIRECT_URL ?? `postgres://mediaos:changeme_dev_only@${host}/${db}`;
  const workerUrl =
    process.env.DATABASE_WORKER_URL ??
    `postgres://mediaos_worker:changeme_worker_only@${host}/${db}`;
  return {
    DATABASE_URL: url,
    DATABASE_DIRECT_URL: directUrl,
    DATABASE_WORKER_URL: workerUrl,
    // G6-2g: int-specs construct SecretRotationService for real. The bypass-RLS guard fail-closes unless
    // this is exactly 'true'. mediaos_worker is non-superuser so the guard is inert here, but set it so
    // the harness is robust if DATABASE_WORKER_URL ever falls back to the superuser direct pool.
    ALLOW_SUPERUSER_ROTATION: "true",
    JWT_SECRET: "test-secret-test-secret-test-secret-test-secret",
    // G16-1b: tắt 2FA-enforcement guard cho harness e2e cũ (admin mock đăng nhập KHÔNG enroll 2FA — bật sẽ
    // 403 mọi route admin). Logic DENY của guard vẫn được phủ ở unit-test (set 'true' tường minh) + tích phân
    // riêng. Prod/staging KHÔNG đặt biến này → default 'true' (BẬT). Chỉ là kill-switch cho test fixtures cũ.
    TWO_FACTOR_ENFORCEMENT_ENABLED: "false",
    // G6-2e: int-specs construct LocalKekProvider for real → must point at the dev KEK. vitest cwd is
    // apps/api, so the env.schema default '.secrets/local-kek.bin' (relative) would miss the repo-root
    // file. Resolve an absolute path from this config's location instead.
    KMS_PROVIDER: "local",
    KMS_LOCAL_KEK_PATH: fileURLToPath(new URL("../../.secrets/local-kek.bin", import.meta.url)),
  };
}

// SWC giữ decorator metadata cho DI của Nest trong test (esbuild của Vitest không emit metadata).
export default defineConfig({
  envDir: ".",
  test: {
    globals: true,
    environment: "node",
    root: ".",
    // *.int-spec.ts = integration (Postgres thật) — tự skip khi không có DATABASE_URL (xem helpers/integration-db).
    include: ["src/**/*.spec.ts", "test/**/*.e2e-spec.ts", "test/**/*.int-spec.ts"],
    // DE-MEDIA-FY (CLAUDE.md reframe 2026-06-20 · S1-QA-DEBT-1): test của module OUT-OF-SCOPE — finance
    // theo-kênh (cost/revenue/cost-allocation) + workflow-DAG (content/project/channel lifecycle). Code đã
    // PARK (không phát triển, không xoá đợt này) ⇒ test của chúng fail-giả che phạm vi THẬT của suite.
    // Exclude (KHÔNG xoá) để dễ un-park sau. KHÔNG đụng approval-FSM (workflow phê duyệt LEAVE/ATT = IN scope).
    // OUT-OF-MVP / Phase-defer (S1-INT-MOUNT-1 — quyết theo SPEC-01 §7.2 + Phase 5): module CHƯA dựng tầng
    // app (route trả 404, KHÔNG phải lỗi) ⇒ exclude deny-test có VÉ PHASE; un-exclude khi build module:
    //   • webhooks-deny → INTEGRATION = Phase 5 (SPEC-01 §7.2/Phase 5, cùng MOBILE/AI).
    //   • ui-config-deny (branding/ui-navigation/i18n-override) → KHÔNG thuộc 7 module MVP (SPEC-01 §7.1);
    //     tùy-biến-giao-diện = giai đoạn sau. (Owner muốn đưa vào MVP → đó là WO BUILD module, không phải mount.)
    exclude: [
      ...configDefaults.exclude,
      // de-media-fy (parked — CLAUDE.md reframe)
      "test/workflow-lifecycle.e2e-spec.ts",
      "test/integration/finance-cost-controller-deny.int-spec.ts",
      "test/integration/finance-cost-allocation-controller-deny.int-spec.ts",
      "test/integration/finance-revenue-controller-deny.int-spec.ts",
      // out-of-MVP / Phase-defer (S1-INT-MOUNT-1)
      "test/integration/webhooks-deny.int-spec.ts",
      "test/integration/ui-config-deny.int-spec.ts",
    ],
    // Integration test mở/đóng pool + chạy DDL → nới timeout mặc định.
    testTimeout: 20000,
    hookTimeout: 30000,
    // Force direct-postgres URL for tests — PgBouncer's auth_query setup requires
    // a userlist.txt generated by setup-db-roles.mjs (not committed).
    // mediaos_app connects directly so RLS is still enforced (role has no BYPASSRLS).
    //
    // PARALLEL LANES (TASKS §5 / MEMORY mediaos-shared-db-drift): each lane MUST verify on its OWN
    // isolated DB `mediaos_<lane>` — drizzle's monotonic-by-`when` migrator SKIPS lower-band migrations
    // forever once a higher band migrates the SHARED `mediaos`, so band-0070s tables would be absent ⇒
    // false green/red. We therefore read the target DB from process.env FIRST (LANE_DB or an explicit
    // DATABASE_URL passed by the lane-db harness); the literals below are only the CI/master fallback.
    // Vitest's `env` literals OVERRIDE process.env, so each URL is resolved here in config (Node ctx)
    // where process.env is authoritative.
    env: laneDbEnv(),
    coverage: {
      provider: "v8",
      // Scoped thresholds (CLAUDE.md §6 / plan G4 §8: "coverage ≥80% — ngưỡng riêng cho module nhạy cảm").
      // Gated ONLY for the two unit-tested crown-jewel files (G4-3 FSM + G4-5 approval). We deliberately do
      // NOT gate the whole src/workflow/** glob: controller/module/dto + workflow.service + workflow.repository
      // are exercised by *.int-spec / *.e2e-spec which skipIf(!DATABASE_URL) — under the no-DB unit run they
      // read as 0–25% and would fail a blanket threshold (false red). Keys are exact paths so per-file vs
      // aggregate semantics are identical. Only active when --coverage is passed (e.g. `pnpm test:cov`).
      thresholds: {
        "src/workflow/workflow-fsm.service.ts": {
          lines: 80,
          functions: 80,
          branches: 80,
          statements: 80,
        },
        "src/workflow/approval.service.ts": {
          lines: 80,
          functions: 80,
          branches: 80,
          statements: 80,
        },
        // G7-2a: DagValidatorService is pure crown-jewel logic — higher bar (plan §4/§6).
        "src/workflow/dag-validator.service.ts": {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        // G7-2b: DAG adapter (port + code map) is pure + fully unit-tested → crown-jewel bar.
        "src/workflow/dag-result.adapter.ts": {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        // G12-1: salary profile service is crown-jewel (lương nhạy cảm) → ≥80% (CLAUDE.md §6).
        "src/payroll/salary-profile.service.ts": {
          lines: 80,
          functions: 80,
          branches: 80,
          statements: 80,
        },
        // S1-FND-SETTING-1: SettingService is crown-jewel (validation_schema + secret-mask + audit-in-tx,
        // CLAUDE.md §6 module nhạy cảm) → ≥80% on all axes. Fully unit-tested (no-DB) so per-file gate is
        // safe (unlike controller/repo exercised only by int-specs). Exact path = per-file semantics.
        "src/foundation/settings/setting.service.ts": {
          lines: 80,
          functions: 80,
          branches: 80,
          statements: 80,
        },
        // S2-QA-1: DataScopeService is crown-jewel (permission data-scope resolver — Own/Team/Dept/Company/
        // System predicate + resolveStrongestScope exact>wildcard, fail-closed null; CLAUDE.md §6 module nhạy
        // cảm) → ≥80% on all axes. Fully unit-tested in the no-DB run via data-scope.service.spec.ts +
        // data-scope.service.coverage.spec.ts (measured 98.83% stmts / 88% branches) so a per-file gate is
        // safe here. Exact path = per-file semantics.
        //
        // WHY auth.service.ts and permission.service.ts are NOT per-file gated here: their real flows
        // (login/refresh/logout/blocked-status; can()/scope resolution against seeded grants) live in
        // *.int-spec.ts that skipIf(!(hasDb && LANE_DB)). In the no-DB unit run those int-specs are skipped,
        // so v8 reads auth.service.ts ≈49.9% stmts and permission.service.ts ≈53–70% stmts — gating them in
        // the default unit run would be a FALSE RED. They follow the SAME LANE_DB caveat as the workflow
        // controller/repo files above: their real coverage number is PRINTED (not gated) by the
        // `test:cov:sensitive` script, which runs the sensitive int-specs under an isolated LANE_DB.
        "src/permission/data-scope.service.ts": {
          lines: 80,
          functions: 80,
          branches: 80,
          statements: 80,
        },
      },
    },
  },
  plugins: [swc.vite()],
});
