import { fileURLToPath } from "node:url";
import swc from "unplugin-swc";
import { defineConfig } from "vitest/config";

// SWC giữ decorator metadata cho DI của Nest trong test (esbuild của Vitest không emit metadata).
export default defineConfig({
  envDir: ".",
  test: {
    globals: true,
    environment: "node",
    root: ".",
    // *.int-spec.ts = integration (Postgres thật) — tự skip khi không có DATABASE_URL (xem helpers/integration-db).
    include: ["src/**/*.spec.ts", "test/**/*.e2e-spec.ts", "test/**/*.int-spec.ts"],
    // Integration test mở/đóng pool + chạy DDL → nới timeout mặc định.
    testTimeout: 20000,
    hookTimeout: 30000,
    // Force direct-postgres URL for tests — PgBouncer's auth_query setup requires
    // a userlist.txt generated by setup-db-roles.mjs (not committed).
    // mediaos_app connects directly so RLS is still enforced (role has no BYPASSRLS).
    env: {
      DATABASE_URL: "postgres://mediaos_app:changeme_app_only@localhost:5432/mediaos",
      DATABASE_DIRECT_URL: "postgres://mediaos:changeme_dev_only@localhost:5432/mediaos",
      DATABASE_WORKER_URL: "postgres://mediaos_worker:changeme_worker_only@localhost:5432/mediaos",
      // G6-2g: int-specs construct SecretRotationService for real. The bypass-RLS guard fail-closes unless this
      // is exactly 'true'. mediaos_worker is non-superuser so the guard is inert here, but set it explicitly so
      // the harness is robust if DATABASE_WORKER_URL ever falls back to the superuser direct pool.
      ALLOW_SUPERUSER_ROTATION: "true",
      JWT_SECRET: "test-secret-test-secret-test-secret-test-secret",
      // G6-2e: int-specs construct LocalKekProvider for real → must point at the dev KEK.
      // vitest cwd is apps/api, so the env.schema default '.secrets/local-kek.bin' (relative) would
      // miss the repo-root file. Resolve an absolute path from this config's location instead.
      KMS_PROVIDER: "local",
      KMS_LOCAL_KEK_PATH: fileURLToPath(new URL("../../.secrets/local-kek.bin", import.meta.url)),
    },
    coverage: {
      provider: "v8",
      // Scoped thresholds (CLAUDE.md §6 / plan G4 §8: "coverage ≥80% — ngưỡng riêng cho module nhạy cảm").
      // Gated ONLY for the two unit-tested crown-jewel files (G4-3 FSM + G4-5 approval). We deliberately do
      // NOT gate the whole src/workflow/** glob: controller/module/dto + workflow.service + workflow.repository
      // are exercised by *.int-spec / *.e2e-spec which skipIf(!DATABASE_URL) — under the no-DB unit run they
      // read as 0–25% and would fail a blanket threshold (false red). Keys are exact paths so per-file vs
      // aggregate semantics are identical. Only active when --coverage is passed (e.g. `pnpm test:cov`).
      thresholds: {
        "src/workflow/workflow-fsm.service.ts": { lines: 80, functions: 80, branches: 80, statements: 80 },
        "src/workflow/approval.service.ts": { lines: 80, functions: 80, branches: 80, statements: 80 },
        // G7-2a: DagValidatorService is pure crown-jewel logic — higher bar (plan §4/§6).
        "src/workflow/dag-validator.service.ts": { lines: 90, functions: 90, branches: 90, statements: 90 },
      },
    },
  },
  plugins: [swc.vite()],
});
